/*
 * Build ledger renderer.
 *
 * Fetches data/ledger.json (generated by tools/build_ledger.py from local
 * Claude Code transcripts — see README) and renders it in two places:
 *   - a one-line stat footer on any project card carrying data-ledger-slug,
 *     matched against the ledger's project slugs
 *   - the #ledger section: sitewide totals, a per-project table, and an
 *     expandable detail row per project (tokens, models, date range)
 *
 * The site otherwise has no build step and no dependencies; this is the
 * only script, kept deliberately small and framework-free to match. If the
 * fetch fails — e.g. index.html opened via file:// instead of served, see
 * README — card footers and the ledger table are simply left empty rather
 * than shown broken.
 */

const MINUS = '−'; // typographic minus, reads better than a hyphen in a negative

function formatCost(usd) {
  return `$${usd.toFixed(2)}`;
}

function formatLines(added, removed) {
  return `+${added.toLocaleString('en-AU')} / ${MINUS}${removed.toLocaleString('en-AU')}`;
}

function formatDateRange(first, last) {
  const fmt = new Intl.DateTimeFormat('en-AU', { day: 'numeric', month: 'short', year: 'numeric' });
  const a = fmt.format(new Date(first));
  const b = fmt.format(new Date(last));
  return a === b ? a : `${a} – ${b}`;
}

function el(tag, className, text) {
  const node = document.createElement(tag);
  if (className) node.className = className;
  if (text != null) node.textContent = text;
  return node;
}

async function loadLedger() {
  const res = await fetch('data/ledger.json');
  if (!res.ok) throw new Error(`ledger fetch failed: ${res.status}`);
  return res.json();
}

// Compact stat line on each project card, linking down to the full section.
function renderCardFooters(ledger) {
  const bySlug = new Map(ledger.projects.map((p) => [p.slug, p]));
  document.querySelectorAll('[data-ledger-slug]').forEach((card) => {
    const project = bySlug.get(card.dataset.ledgerSlug);
    if (!project) return;

    const footer = el('div', 'card-ledger');
    footer.append(el(
      'span',
      'card-ledger-stats',
      `${project.sessions} session${project.sessions === 1 ? '' : 's'} · ${formatCost(project.cost_usd)} · ${formatLines(project.lines_added, project.lines_removed)}`,
    ));
    const link = el('a', 'card-ledger-link', 'ledger ↓');
    link.href = '#ledger';
    footer.append(link);
    card.append(footer);
  });
}

// Sitewide totals strip and the "NNN PROJECTS TRACKED" count in the section header.
function renderTotals(ledger) {
  const t = ledger.totals;
  const strip = document.querySelector('.ledger-totals');
  if (strip) {
    strip.textContent = `${t.sessions} sessions · ${t.human_turns} turns · ${formatCost(t.cost_usd)} API-equiv · ${formatLines(t.lines_added, t.lines_removed)}`;
  }
  const count = document.querySelector('.ledger-count');
  if (count) {
    count.textContent = `${String(t.projects).padStart(3, '0')} PROJECTS TRACKED`;
  }
}

// Per-project table row plus a hidden detail row toggled open by the trailing button.
function renderTable(ledger) {
  const body = document.querySelector('.ledger-table tbody');
  if (!body) return;
  body.innerHTML = '';

  ledger.projects.forEach((project) => {
    const row = el('tr', 'ledger-row');
    row.append(
      el('td', 'ledger-cell ledger-cell-name', project.name),
      el('td', 'ledger-cell', String(project.sessions)),
      el('td', 'ledger-cell', String(project.human_turns)),
      el('td', 'ledger-cell', formatCost(project.cost_usd) + (project.estimated_cost_sessions ? '*' : '')),
      el('td', 'ledger-cell', formatLines(project.lines_added, project.lines_removed)),
    );

    const toggle = el('button', 'ledger-toggle', '+');
    toggle.type = 'button';
    toggle.setAttribute('aria-expanded', 'false');
    toggle.setAttribute('aria-label', `Show build detail for ${project.name}`);
    const toggleCell = el('td', 'ledger-cell ledger-cell-toggle');
    toggleCell.append(toggle);
    row.append(toggleCell);

    const detailRow = el('tr', 'ledger-detail-row');
    detailRow.hidden = true;
    const detailCell = el('td', 'ledger-detail-cell');
    detailCell.colSpan = 6;

    const models = project.models.filter((m) => m !== '<synthetic>').join(', ');
    const detailLines = [
      `models: ${models || 'n/a'}`,
      `tokens: ${project.tokens.input.toLocaleString('en-AU')} in / ${project.tokens.output.toLocaleString('en-AU')} out / ${project.tokens.cache_read.toLocaleString('en-AU')} cache-read / ${project.tokens.cache_creation.toLocaleString('en-AU')} cache-write`,
      `built: ${formatDateRange(project.first_session, project.last_session)}`,
    ];
    if (project.estimated_cost_sessions) {
      detailLines.push(`* ${project.estimated_cost_sessions} of ${project.sessions} session${project.sessions === 1 ? '' : 's'} priced from token counts, not a cost Claude Code recorded itself`);
    }
    if (project.unpriced_models.length) {
      detailLines.push(`note: cost excludes usage under unpriced model(s) ${project.unpriced_models.join(', ')}`);
    }
    detailLines.forEach((line) => detailCell.append(el('p', 'ledger-detail-line', line)));
    detailRow.append(detailCell);

    toggle.addEventListener('click', () => {
      const expanded = toggle.getAttribute('aria-expanded') === 'true';
      toggle.setAttribute('aria-expanded', String(!expanded));
      toggle.textContent = expanded ? '+' : MINUS;
      detailRow.hidden = expanded;
    });

    body.append(row, detailRow);
  });
}

// Caveats from the ledger data itself (e.g. "costs are API-equivalent, not
// money paid") — sourced from the JSON so the wording only has to live in
// tools/build_ledger.py, not be kept in sync with this file by hand.
function renderNotes(ledger) {
  const notes = document.querySelector('.ledger-notes');
  if (!notes) return;
  notes.innerHTML = '';
  ledger.notes.forEach((note) => notes.append(el('p', 'ledger-note', note)));
}

loadLedger()
  .then((ledger) => {
    renderCardFooters(ledger);
    renderTotals(ledger);
    renderTable(ledger);
    renderNotes(ledger);
  })
  .catch((err) => {
    // Non-fatal — the rest of the page works fine without the ledger.
    console.warn('Build ledger not loaded:', err);
  });
